### ISSUE TITLE
404 when trying to load

### ISSUE THREAD

**Issue by darrynhoskingluna** [wouterdebie/putioarr#1]
I get a 404 when navigating to the exposed port 9091.

**Environment**
Docker

**Docker**
`version: "2.1"
services:
  putioarr:
    image: ghcr.io/wouterdebie/putioarr:latest
    container_name: putioarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./putioarr/config:/config
      - ./content/downloads:/downloads
    ports:
      - 9091:9091
    restart: unless-stopped`

**Additional context**
Does this project have a administrative web ui? I may be assuming here it was not clear in the documentation

**Comment by wouterdebie** [comment]
The project does not have an admin UI and there's nothing at `/`. The API that sonarr/radarr uses is at `/transmisison`, but that's not for human consumption.
