### ISSUE TITLE
Bypass downloading files locally after completion 

### ISSUE THREAD

**Issue by shardulbee** [wouterdebie/putioarr#2]
**Is your feature request related to a problem? Please describe.**
I am storage-constrained on my computer and do not have the space to have local copies of files downloaded to put.io locally. 

**Describe the solution you'd like**
Skip the local downloading of files from put.io to the configurable storage location. 

**Describe alternatives you've considered**
It would be cool to be able to transfer completed files to Dropbox/Google Drive!

**Comment by wouterdebie** [comment]
I'll implement the option to not download. The issue however is that your radarr/sonarr will not import it either. In this case, I think it'd be best to remove the transfer from put.io (while leaving the files there).

On the Dropbox/Gdrive, I'd recommend using rclone and mounting those in order to write to.

**Comment by shardulbee** [comment]
Hmm, I never considered using `rclone`. I've never used it, but based on some reading it sounds like it would be possible to set putioarr's download directory as a GDrive mount, right? Would sonarr/radarr then be able to access those files?

**Comment by wouterdebie** [comment]
What I would do is to have `putioarr` download to a local directory that sonarr/radarr have as their download directory. Then use `rclone` to mount a GDrive that sonarr/radarr have as their storage directories. Once putioarr completes downloading, sonarr/radarr will import the download and move it to their storage directory (which is on GDrive).

**Comment by shardulbee** [comment]
Cool, I think that would work for me. I probably don't need this feature solved then. You can close it out if you'd like

**Comment by wouterdebie** [comment]
Awesome! I'll do that!
