### ISSUE TITLE
putioarr stopps downloading from put.io

### ISSUE THREAD

**Issue by thaussma** [wouterdebie/putioarr#3]
**Describe the bug**
After using putioarr for some time (~7days) it does not download finished media files from put.io any more. Restarting putioarr does not help either. When this is the case the log always shows an exception:

```
thread 'main' panicked at src/download_system/transfer.rs:108:40:
called `Option::unwrap()` on a `None` value
```

When I remove all transfers on put.io, putioarr works properly again (though I have to readd all downloads). But then the issue pops up again in about a week.

**To Reproduce**
I do not know how to reproduce it. 

**Logs**
Please provide any logs that show the error.

**Configuration**
```
username = "x"
password = "x"
download_directory = "/downloads"
bind_address = "0.0.0.0"
port = 9091
loglevel = "info"
uid = 1000
polling_interval = 10
skip_directories = ["sample", "extras"]
orchestration_workers = 6
download_workers = 2

[putio]
api_key =  "x"

[sonarr]
url = "http://x:x"
api_key = "x"
```

**Environment**
I use [ghcr.io/wouterdebie/putioarr:latest](https://github.com/wouterdebie/putioarr/pkgs/container/putioarr/151921704?tag=v0.5.15) on [unraid](https://unraid.net/).

**Comment by wouterdebie** [comment]
Thanks for the bug report! I missed a default value. This should be fixed soon.
